The actions : post, list and toggle are now functions. It will be easier to do changes if needed.

diff --git a/baker b/baker
--- a/baker
+++ b/baker
@@ -266,6 +266,70 @@ render_file() {
 	echo "$content"
 }
 
+# post_toggle toggles the status of a post (either use ID or post name)
+post_toggle() {
+	local _fname=''
+	if [ -z "${1:-}" ]; then
+		usage
+	elif [ -z "${1//[0-9]/}" ]; then
+		readarray -t posts < <(find "$POST_DIR" -name '*.md' | sort -r)
+		if [ ${1} -lt ${#posts[@]} ]; then
+			_fname="${posts[${1}]}"
+		fi
+	elif [ -f "${POST_DIR}/${1}" -o -f "${POST_DIR}/${1}.md" ]; then
+		_fname="${POST_DIR}/${1//\.md/}.md"
+	fi
+	if [ -z "${_fname}" ]; then
+		echo "This post doesn't exist"
+		exit 1
+	fi
+	if [ "$(header draft < "${_fname}")" == 'false' ]; then
+		sed -i -e 's;^[[:space:]]*draft:[[:space:]]*false[[:space:]]*$;draft: true;g'  "${_fname}"
+	else
+		sed -i -e 's;^[[:space:]]*draft:[[:space:]]*.*[[:space:]]*$;draft: false;g'  "${_fname}"
+	fi
+}
+
+# post_list list the id title and status of posts
+post_list() {
+	local idx=0
+	readarray -t posts < <(find "$POST_DIR" -name '*.md' | sort -r)
+	(
+		echo "id title status"
+		for post in "${posts[@]}"; do
+			id="$(basename "$post" .md)"
+			# skip drafts
+			if [ "$(header draft < "$post")" == 'false' ]; then
+				echo "${idx} $id [Published]"
+			else
+				echo "${idx} $id [Draft]"
+			fi
+			((idx++))
+		done
+	) | column -t
+}
+
+# post_post creates a post (in the POST_DIR) with the minimum information 
+post_post() {
+	readonly title="${@}"
+	[[ "$title" ]] || usage
+
+	mkdir -p "$POST_DIR" || ( echo "Can't create '$POST_DIR'" >&2; exit 1 )
+	readonly post_file="$POST_DIR/$(date +%Y-%m-%d)-$(slug <<< "$title").md"
+	cat > "$post_file" <<-EOF
+	---
+	title: $title
+	date: $(date -u +%FT%TZ)
+	layout: post
+	draft: true
+	summary:
+	---
+	EOF
+
+	echo "$post_file"
+	[[ "$EDITOR" ]] && $EDITOR "$post_file"
+}
+
 #
 # usage
 #
@@ -343,62 +407,13 @@ bake)
 	wait
 	;;
 post)
-	readonly title="${@:2}"
-	[[ "$title" ]] || usage
-
-	mkdir -p "$POST_DIR"
-	readonly post_file="$POST_DIR/$(date +%Y-%m-%d)-$(slug <<< "$title").md"
-	cat > "$post_file" <<-EOF
-	---
-	title: $title
-	date: $(date -u +%FT%TZ)
-	layout: post
-	draft: true
-	summary:
-	---
-	EOF
-
-	echo "$post_file"
-	[[ "$EDITOR" ]] && $EDITOR "$post_file"
+	post_post "${@:2}"
 	;;
 list)
-	idx=0
-	readarray -t posts < <(find "$POST_DIR" -name '*.md' | sort -r)
-	(
-		echo "id title status"
-		for post in "${posts[@]}"; do
-			id="$(basename "$post" .md)"
-			# skip drafts
-			if [ "$(header draft < "$post")" == 'false' ]; then
-				echo "${idx} $id [Published]"
-			else
-				echo "${idx} $id [Draft]"
-			fi
-			((idx++))
-		done
-	) | column -t
+	post_list
 	;;
 toggle)
-	_fname=''
-	readarray -t posts < <(find "$POST_DIR" -name '*.md' | sort -r)
-	if [ -z "${2:-}" ]; then
-		usage
-	elif [ -z "${2//[0-9]/}" ]; then
-		if [ ${2} -lt ${#posts[@]} ]; then
-			_fname="${posts[${2}]}"
-		fi
-	elif [ -f "${POST_DIR}/${2}" -o -f "${POST_DIR}/${2}.md" ]; then
-		_fname="${POST_DIR}/${2//\.md/}.md"
-	fi
-	if [ -z "${_fname}" ]; then
-		echo "This post doesn't exist"
-		exit 1
-	fi
-	if [ "$(header draft < "${_fname}")" == 'false' ]; then
-		sed -i -e 's;^[[:space:]]*draft:[[:space:]]*false[[:space:]]*$;draft: true;g'  "${_fname}"
-	else
-		sed -i -e 's;^[[:space:]]*draft:[[:space:]]*.*[[:space:]]*$;draft: false;g'  "${_fname}"
-	fi
+	post_toggle "${@:2}"
 	;;
 *)
 	usage
